# Generated by Django 4.2.6 on 2023-10-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('sign_of_a_pleasant_habit', models.BooleanField(blank=True, default=0, null=True, verbose_name='признак приятной привычки')),
                ('periodicity_in_week', models.SmallIntegerField(verbose_name='переодичность в неделю ')),
                ('reward', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='награда')),
                ('time_to_complete', models.IntegerField(blank=True, default=0, null=True, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=0, verbose_name='признак публичности')),
                ('last_send', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время последней отправки напоминания')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
