# Generated by Django 4.2.6 on 2023-10-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('sign_of_a_pleasant_habit', models.BooleanField(blank=True, default=0, null=True, verbose_name='признак приятной привычки')),
                ('related_habit', models.BooleanField(blank=True, default=0, null=True, verbose_name='Связанная привычка')),
                ('periodicity', models.CharField(choices=[('раз в час', 'once an hour'), ('раз в день', 'once a day'), ('раз в неделю', 'once a week')], default='once a day', max_length=20, verbose_name='переодичность')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='награда')),
                ('time_to_complete', models.TimeField(default=0, verbose_name='время на выполнение')),
                ('sign_of_publicity', models.BooleanField(default=0, verbose_name='признак публичности')),
                ('related_habit_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
